# Generated by Django 3.0.6 on 2020-06-29 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Category')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=63)),
                ('unsel_fg_color', models.CharField(max_length=15)),
                ('unsel_bg_color', models.CharField(max_length=15)),
                ('sel_fg_color', models.CharField(max_length=15)),
                ('sel_bg_color', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('home_account', models.CharField(max_length=255)),
                ('unknown_account', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checknum', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('amount', models.IntegerField()),
                ('status', models.IntegerField()),
                ('transdate', models.DateTimeField()),
                ('fitid', models.CharField(blank=True, max_length=255)),
                ('transdest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transdest', to='ledger.Entity')),
                ('transsource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transsource', to='ledger.Entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.User')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.User'),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.User'),
        ),
        migrations.CreateModel(
            name='BanknameLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankname', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.User')),
            ],
        ),
    ]
