# Generated by Django 3.0.6 on 2020-06-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='fitid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
