# Generated by Django 3.1 on 2021-02-16 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20200704_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='home_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_account', to='ledger.entity'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='unknown_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unknown_account', to='ledger.entity'),
        ),
    ]
