# Generated by Django 3.1 on 2021-02-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_auto_20210215_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='bankname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
